apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addons.lstack.k8s.io
spec:
  group: lstack.k8s.io
  version: v1
  names:
    kind: Addon
    plural: addons
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        spec:
          properties:
            version:
              description: "Version of addon."
              type: string
            chartAddr:
              type: string
            addonTemplateName:
              type: string
            addonTemplateLogo:
              type: string
            values:
              type: string
            addonTemplateType:
              type: string
            description:
              type: string
            addonTemplateLabels:
              items:
                type: string
              type: array
            basicValues:
              type: string
  additionalPrinterColumns:
  - name: status
    type: string
    JSONPath: .status.status
  - name: Version
    type: string
    JSONPath: .spec.version
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestampku c
  subresources:
    status: {}