apiVersion: v1
kind: ServiceAccount
metadata:
  name: addon-controller
  namespace: lstack-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-controller
  namespace: lstack-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: addon-controller
    namespace: lstack-system